journey
    title My working day
    section Morning
      Make tea: 5: Me
      Go upstairs: 3: Me
      Do work: 1: Me, Cat
    section Afternoon
      Eat lunch: 2: Me
      More work: 1: Me, Cat


